# Crawler Configuration

# Project and Target Settings
project_name:  # From Project_name_c
homepage_url:  # From Home_page_c
domain_name:  # Ensure this matches your homepage_url's domain

# Exclusions for Content Parsing
# These lists are directly moved from your EXCLUDE_TAGS and EXCLUDE_CLASSES
exclude_tags:
  - nav
  - script
  - style
  - header
  - footer
  - figure
exclude_classes:
  - header__inner
  - social-share__title
  - social-share__items
  - content-group__title
  - content-group__body has-columns-4
  - footer f156hidz
  - footer__column footer__column--5
  - footer__column-content
  - logo logo--full footer__logo l979h8x
  - footer__details
  - footer__address
  - footer__copyright
  - footer__social
  - footer__social-link
  - footer__social-icon
  - footer__social-text
  - simple-menu__link
  - simple-menu__item
  - list simple-menu__list

# Data Extraction Features
summary_mode: false # From Summery_Mode

# Performance Settings
number_of_threads: 8 # From Number_of_threads_c

# API/Model Settings (if you're using external AI models for summarization, etc.)
# You'd typically only include these if you're actually calling these APIs.
# If you don't need these in your current spider, you can omit this section.
api_settings:
  default_model: gemma_3_27b_it # Or 'gemini-1.5-flash'
  available_models:
    - gemini-1.5-flash
    - gemma-3-27b-it
  gemini_1_5_flash:
    calls_per_minute: 15
    period_milliseconds: 500 # Your daily budget in terms of requests per day
  gemma_3_27b_it:
    calls_per_minute: 15
    period_milliseconds: 14400

# Anti-Blocking Measures (keeping these from previous example)
min_delay_seconds: 1.5
max_delay_seconds: 4.0

# Database Settings (keeping these from previous example)
database_filename: scraped_data.db

# Anti-Blocking Measures
min_delay_seconds: 1.5 # Minimum random delay between requests
max_delay_seconds: 4.0 # Maximum random delay between requests

# User Agents for mimicking browsers (moved from User_agents.py)
user_agents:
  # --- Chrome on various OS ---
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/125.0.0.0 Mobile/15E148 Safari/604.1"
  - "Mozilla/5.0 (iPad; CPU OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/124.0.0.0 Mobile/15E148 Safari/604.1"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; CrOS x86_64 15816.69.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36"
  - "Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36"


  # --- Firefox on various OS ---
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0"
  - "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:125.0) Gecko/20100101 Firefox/125.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0"
  - "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
  - "Mozilla/5.0 (Android 10; Mobile; rv:126.0) Gecko/20100101 Firefox/126.0"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7_2 like Mac OS X; rv:126.0) Gecko/20100101 Firefox/126.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.4; rv:126.0) Gecko/20100101 Firefox/126.0"
  - "Mozilla/5.0 (Windows NT 11.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
  - "Mozilla/5.0 (Linux; Android 14; SM-G996B; rv:126.0) Gecko/20100101 Firefox/126.0"


  # --- Edge on various OS ---
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.2535.79"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.2478.67"
  - "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36 EdgA/125.0.2535.79"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 EdgiOS/125.0.2535.79 Mobile/15E148 Safari/605.1.15"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Brave/125.1.63.165"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Brave/124.1.60.118"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.2592.47"


  # --- Safari on macOS/iOS ---
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
  - "Mozilla/5.0 (iPad; CPU OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"


  - "Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/125.0.0.0 Mobile Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Vivaldi/6.7.3329.29"


  # --- Older/Less Common Browsers (for diversity) ---
  - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" # Ubuntu Firefox
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 OPR/111.0.0.0" # Opera
  - "Mozilla/5.0 (SMART-TV; Linux; Tizen 6.5) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 TV Safari/537.36"

